#!/usr/bin/zsh

# adjust brightness levels
# support for a laptop and one external monitor through xrandr brightness
# occasionally it takes a while to run xbacklight after xrandr, is prob kernel issue

# change this to match your external monitor's name.
# if you don't know it, run `xrandr | grep 'connected | grep -v 'dis'`
extConnected=false
extMonitor=HDMI-0
extStatus="$( xrandr | awk "/$extMonitor/"'{print $2}' )"
backlight="$( xbacklight )"

if [[ "${extStatus}" == connected ]]; then
	extBright=$( xrandr --verbose \
		| grep -A5 "${extMonitor}" \
		| awk -F' ' '/Brightness/{print $2}')
	extConnected=true
fi

lower() {
	# lower brightness of laptop brightness and ext monitor
	if [[ -n "${extConnected}" ]]; then
		if (( extBright > 0.2 )); then
			xrandr --output "${extMonitor}" --brightness "$(( extBright - 0.05 ))"
		fi
	fi
	if (( backlight > 20 )); then
		xbacklight -dec 5
	fi
	return
}

raise() {
	# raise brightness of laptop and ext monitor
	if [[ -n "${extConnected}" ]]; then
		if (( extBright <= 1.0 )); then
			xrandr --output "${extMonitor}" --brightness "$(( extBright + 0.05 ))"
		fi
	fi
	if (( backlight <= 100 )); then
		xbacklight -inc 5
	fi
	return
}

min() {
	# set monitors to lowest brightness
	if [[ -n "${extConnected}" ]]; then
		xrandr --output "${extMonitor}" --brightness 0.2
	fi
	xbacklight -set 20
}

max() {
	# set monitors to highest brightness
	if [[ -n "${extConnected}" ]]; then
		xrandr --output "${extMonitor}" --brightness 1.0
	fi
	xbacklight -set 100
}

main() {
	case "$1" in
		--lower)
			lower
			;;
		--raise)
			raise
			;;
		--min)
			min
			;;
		--max)
			max
		;;
	esac
	exit 0
}

main "$@"
