#!/usr/bin/env bash
# check if external display is plugged in, launch all utilities

connected="$(xrandr | awk '/HDMI-0/ {print $2}')"
wallpapers="${HOME}/documents/pictures/wallpapers"

launch_picom() {
	killall -q picom
	while pgrep -u "${UID}" -x picom >/dev/null; do sleep 1; done
	nohup picom --experimental-backends </dev/null >/dev/null 2>&1 &
}

# set up monitors and wallpapers
if [[ "${connected}" == connected ]]; then
	xrandr --output HDMI-0 --auto --above DP-0
	feh --no-fehbg --bg-fill -- "${wallpapers}/desktop0.png" "${wallpapers}/desktop1.png"
elif [[ "${connected}" == disconnected ]]; then
	xrandr --output HDMI-0 --off --auto
	feh --no-fehbg --bg-fill -- "${wallpapers}/desktop1.png"
else
	exit 1
fi

# notifications
nohup dunst -config "${XDG_CONFIG_HOME}/dunst/dunstrc" </dev/null >/dev/null 2>&1 &

# bar
"${XDG_CONFIG_HOME}/polybar/scripts/launch.sh"

# compositor
launch_picom

exit 0
