#!/usr/bin/bash
# select a gitignore for the current directory

gitignore_dir="${HOME}/templates/gitignore"

main() {
    if [[ ! -d "$gitignore_dir" ]]; then
        echo "Cloning gitignore repository..."
        git clone "https://github.com/github/gitignore" "$gitignore_dir" || exit 1
        echo "gitignores cloned to $gitignore_dir"
    fi

    declare -A gitignores

    # TODO: add support for other dirs in repo
    for f in "$gitignore_dir"/*.gitignore; do
        gitignores+=(["$(basename "$f")"]="$f")
    done

    chosen="$(echo "${!gitignores[@]}" | tr " " '\n' | fzf +m)"
    cp -i -- "${gitignores[$chosen]}" ./.gitignore
}

main "$@"
