#!/bin/bash

# shellcheck disable=SC2016
config_file="${XDG_CONFIG_HOME}/i3/config"
ws_regex='workspace \$ws([0-9]|10) gaps (top|bottom) [0-9]{2}'

comment_lines() {
    # removes gaps
    sed -Ei "/${ws_regex}/ s/^/# /" "$config_file"
    gap_status="disabled"
}

uncomment_lines() {
    # adds gaps
    sed -Ei "/${ws_regex}/ s/^# //" "$config_file"
    gap_status="enabled"
}


if grep -q '^workspace \$' "$config_file"; then
    comment_lines
else
    uncomment_lines
fi
#
# if ! xprop &>/dev/null; then
#     i3-msg "reload" >/dev/null
#     notify-send "i3 gaps ${gap_status}"
# fi
