#!/usr/bin/env bash
# create or edit a note file

# TODO default to creating year and month dirs, use current day as default note name
ft="md"
note_name="$( date -I )"
note_dir="${HOME}/documents/personal/notes"

current_year="$( date +"%Y" )"
current_month="$( date +"%m" )"

year_dir="${note_dir}/${current_year}"
month_dir="${year_dir}/${current_month}"

create_dir() {
    # TODO operate on "$1", which is note-dir (defaults to month dir)
    if [[ ! -d "$month_dir" ]]; then
        mkdir -p -- "$month_dir"
    fi
}

create_note() {
    create_dir "$1"
    "$EDITOR" -- "${1}/${2}.${3}"
}

usage() {
    cat << EOF
Usage: note [<args>]

Arguments are:
    -h, --help      Display this help
    -l, --latex     Create the note as a .latex file
    -n, --name      Set the name of the note
    --note-dir      Directory to store the note in
    -m, --markdown  Create the note as a .md file (default)
    -t, --text      Create the note as a .txt file
EOF
}


# handle arguments
TEMP=$( getopt -o 'hlmn:t' -l 'help,latex,markdown,name:,note-dir:,text' -n 'note' -- "$@" )
eval set -- "$TEMP"
unset TEMP

while true; do
    case "$1" in
        '-h'|'--help')
            usage
            ;;
        '-l'|'--latex')
            ft="latex"
            shift
            continue
            ;;
        '-m'|'--markdown')
            ft="md"
            shift
            continue
            ;;
        '-n'|'--name')
            note_name="$2"
            shift 2
            continue
            ;;
        '--note-dir')
            note_dir="$2"
            shift 2
            continue
            ;;
        '-t'|'--txt')
            ft="txt"
            shift
            continue
            ;;
        '--')
            shift
            break
            ;;
        *)
            echo "$2 is not a recognized argument"
            exit 1
            ;;
    esac
done

create_note  "$note_dir" "$note_name" "$ft"
