#!/bin/sh
# Pacman INTeractive scripts
# starting oneliners taken from the archwiki, this is just a wrapper

pint_install() {
  yay -Slq | fzf -m --height=100% --preview='yay -Si {1}' | xargs -ro sudo yay -S
}

pint_uninstall() {
  yay -Qq | fzf -m --height=100% --preview 'yay -Qi {1}' | xargs -ro sudo yay -Rns
}

print_error() {
  tput setaf 1
  printf -- '[ERR] %s\n' "$*" >&2
  tput sgr0
  usage
  exit 1
}

usage() {
  cat <<EOF
Usage: pint <command> [<args>]

Commands are:
    -R  Remove installed packages
    -S  Install packages
EOF
}

echo "NOT WORKING"
exit 1

if [ $# -gt 1 ]; then
  print_error "pint only takes one argument at a time"
elif [ $# -eq 0 ]; then
  print_error "Please provide an argument"
fi

case "$1" in
-R | remove | Remove)
  pint_uninstall
  ;;
-S | install | Install)
  pint_install
  ;;
*)
  print_error "No such command '$1'"
  ;;
esac
