#!/usr/bin/env bash
# upload a file to ffsend, and email the link
# requires ffsend and a mail client

usage() {
  cat <<EOF
Usage: sendfile <file> <recipient>
EOF
  exit 0
}

sendfile() {
  # upload a file to the ffsend service and email the link to a recipient
  # $1 is file to send, $2 is the recipient
  local subject="${1%.*}" # remove file extension
  ffsend upload -acIqy "$1" | sed 's/^/URL: /' | mail -s "$subject" "$2"
}

if (("$#" == 0)); then
  usage
else
  sendfile "$@"
fi

exit 0
