#!/bin/sh
# quick programs to run on startup

# enable numslock
numlockx &

# remove active tag from completed TODO: items
# the "/- \[ \]!" means "ignore lines starting with this pattern"
perl -pi -e '/- \[ \]/!s/<\!--a-->//' "${HOME}/lib/TODO.md"

# lock screen after 10 minutes of inactivity
xset s on
xset s 600
xss-lock physlock
