#!/usr/bin/env bash
set -euo pipefail

informant check; INF_UPDATES=$?
if [[ $INF_UPDATES != 0 ]]; then
	informant list
	printf 'Read new bulletins? '; read -r response
	case $response in
	    y|Y)
		informant read	;;
	    *)
		printf 'Skipping read.\n'
	esac
else
    printf 'No updates to Arch News.\n'
fi

printf 'Proceed with main update? '; read -r response
case $response in
    y|Y)
	pacman -Syu
	printf 'Also update AUR packages? '; read -r response
	case $response in
	    y|Y)
		sudo -u jam yay -Syua  ;;
	    *)
		printf 'Skipping AUR packages.\n'
	esac ;;
    *)
	printf 'Cancelling update.\n'
	exit 0
esac

lastDate=$(cat /home/jam/.zinit/.lastDate)
currentDate=$(date "+%y%m%d")
if [ $((lastDate + 7)) -lt "$currentDate" ]; then
    sudo -u jam zsh /home/jam/bin/runZinit.sh
    printf '\nzinit updated, moving onto tldr cache.\n'
    /usr/bin/tldr --update
    /home/jam/bin/get-installed.sh
	/home/jam/bin/update-pip.sh
    printf "%s\n" "$currentDate" > /home/jam/.zinit/.lastDate
    printf "Next full update will run on or after %d.\n" "$(( currentDate + 7 ))"
## TODO !! Add updater for cargo
fi

exit 0

