#!/usr/bin/env bash
# run usbguard interactively to avoid typing two commands lol

checkRoot() {
	if (( "$( id -u )" != 0 )) || ! hash usbguard 2> /dev/null; then
		print_error "Make sure 'usbguard' is installed and run as root."
	fi
}

print_error() {
	tput setaf 1
	printf -- '[ERR] %s\n' "$1" >&2
	tput sgr0
	exit 1
}
# TODO option to set rules instead of one-time actions
main() {
	checkRoot
	printf -- '%s\n\n' "USB Devices:"
	usbguard list-devices
	printf -- '\n'
	read -rp "Which device would you like to operate on? " device
	read -rp "[a]llow, [b]lock, or [r]eject device? " operation
	case "$operation" in
		a|A|allow|Allow)
			operation="allow-device"
			;;
		b|B|block|Block)
			operation="block-device"
			;;
		r|R|reject|Reject)
			operation="reject-device"
			;;
		*)
			print_error "Please select an option between: [a]llow [b]lock [r]eject"
	esac
	usbguard "${operation}" "${device}"
}

main
unset device
unset operation
exit 0
