#!/usr/bin/env bash
# change volume with notifications

msg_id="991049"

amixer -c 0 set Master "$@" >/dev/null

volume="$(amixer -c 0 get Master | tail -n1 | awk '{print $4}' | tr -d '[]%')"
mute="$(amixer -c 0 get Master | tail -n1 | awk '{print $6}' | tr -d '[]')"

if [[ "$volume" == 0 || "$mute" == off ]]; then
  dunstify -a "Volume" -u low -i audio-volume-muted -r "$msg_id" "Volume Muted"
else
  dunstify -a "Volume" -u low -i audio-volume-high -r "$msg_id" \
    -h int:value:"$volume" "Volume: ${volume}%"
fi
