#!/usr/bin/env bash
# The bulk of this code is taken from <wttr.in/:bash.function>
# If you source this file, it will set WTTR_PARAMS as well as show weather.

usage() {
    cat << EOF
Usage: wttr <location> [<range>]

Locations can be:
    City Name:     los+angeles
    Location:      eiffel+tower
    Airport Code:  jfk
    Domain Name:   @stackoverflow.com
    Area Code:     90210
    Coordinates:   -78.46,106.79

Ranges are:
    0  Only current weather
    1  Current weather + today's forecast
    2  Current weather + today's forecast + tomorrow's forecast (default)
EOF
exit 0
}

# WTTR_PARAMS is space-separated URL parameters, many of which are single characters that can be
# lumped together. For example, "F q m" behaves the same as "Fqm".
if [[ -z "$WTTR_PARAMS" ]]; then
  # Form localized URL parameters for curl
  if [[ -t 1 ]] && [[ "$(tput cols)" -lt 125 ]]; then
      WTTR_PARAMS+='n'
  fi 2> /dev/null
  for _token in $( locale LC_MEASUREMENT ); do
    case $_token in
      1) WTTR_PARAMS+='m' ;;
      2) WTTR_PARAMS+='u' ;;
    esac
  done 2> /dev/null
  unset _token
  export WTTR_PARAMS
fi

wttr() {
  if [[ "$1" == help ]]; then
      usage
  fi
  local location="${1// /+}"
  command shift
  local args=""
  for p in $WTTR_PARAMS "$@"; do
    args+=" --data-urlencode $p "
  done
  curl -fGsS -H "Accept-Language: ${LANG%_*}" \
      $args --compressed "wttr.in/${location}?${2:+}"
}

wttr "$@"
